version: "2"
services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_HOST:db
      - WORDPRESS_DB_USER:admin
      - WORDPRESS_DB_PASSWORD:admin
      - WORDPRESS_DB_NAME:wordpress
    volumes:
      - /opt/lampp/htdocs/site_lr:/var/www/html:rw
    links:
      - db:db

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE:wordpress
      - MYSQL_USER:admin
      - MYSQL_PASSWORD:admin

  adminer:
    image: adminer
    ports:
      - 8083:8080
    depends_on:
      - db

